##############
# MEDIA
##############

### Create a Medium entity simplest mode
POST http://{{host}}/api/entities HTTP/1.1
content-type: application/json
accept: application/json

{
    "model": "Medium"
}

### List all media
GET http://{{host}}/api/entities?select=id,model&of-model=Medium HTTP/1.1
accept: application/json

### Upload a file
POST http://{{host}}/api/media/8jlPk7wG2j/upload HTTP/1.1
accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="pan.jpg"
Content-Type: image/jpeg

< ./parts/pan.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Clear cache of a medium
DELETE http://{{host}}/api/media/3H-QQ4E0Yt/static/icon HTTP/1.1
content-type: application/json
accept: application/json

### Clear cache of all media
DELETE http://{{host}}/api/media/*/static/icon HTTP/1.1
content-type: application/json
accept: application/json

### Clear cache of all media all presets
DELETE http://{{host}}/api/media/*/static HTTP/1.1
content-type: application/json
accept: application/json

### Hard Delete an entity
DELETE http://{{host}}/api/entities/vmU4YzozuA?hard=true HTTP/1.1
accept: application/json


