# @name csrf
GET http://{{host}}/sanctum/csrf-cookie

###

@csrfToken = eyJpdiI6IjY0RlB2NjVWU3dvZ2NqVEdFN0Nka3c9PSIsInZhbHVlIjoiUFFiUTRGL2ZzVkdqMFp6SjlFdHlBWmd3WmF1cEUzMXhWSWZodERJRnBqME9ZOGcvVk1aZHVhaG1WbDhma1JHYmlEcW94QW1iMTJDc1dOTWkzZWJUb0prR2RvUklRY21wYjRQZ0kzR0g3SlIrd1liMUdEeUJwdUNvQ0FrT0x2dEIiLCJtYWMiOiJhZGM5ZjI0ZmYyZWRiNzdlOTRlNzg0ZmQ2MmM1ZWQ3MDYwYzQyZmJjOGFhOGM0NWY4MzUyYjRhODBkM2JkYmE5In0

### Login
POST http://{{host}}/api/auth/login HTTP/1.1
x-xsrf-token: {{csrfToken}}
content-type: application/json
accept: application/json

{
    "email": "admin@example.comx",
    "password": "605fc6b3c8d9c5.19302828"
}