# @name csrf
GET http://{{host}}/sanctum/csrf-cookie

###

@csrfToken = eyJpdiI6IlFtMkVWVk5zZFh2K3EwOEQxNDE4TGc9PSIsInZhbHVlIjoiUXhITmt2dnBpbFlUcnVHNldJTlZPOUtvREIveFQvQXM0WWxKNE9NQ3o5bXRybGhWOCtvQzZOMVZiZERNbEwyQjB2SHd2N2lpVkJ5NENWSFIyZXFIOUprc0cxOElJNzBtMFZZTUd6QTN0VDBydzJmK2VpS01WYWh4Ui9ncFVuNWQiLCJtYWMiOiI3ZTNjMWQyMTI1MDMyMDM2YjM0ZGI1YzMwZWY1NDJjNTM3NGE5MGNkMWY2ZWFjZDIxZjBmNzZhYTVhYTYyNzM4In0

### Login
POST http://{{host}}/api/auth/login HTTP/1.1
x-xsrf-token: {{csrfToken}}
content-type: application/json
accept: application/json

{
    "email": "admin@example.com",
    "password": "605fc6b3c8d9c5.19302828"
}