language: php

php:
  - 8.0

env:
  matrix:
    - COMPOSER_OPTIONS=""

before_install:
  - sudo apt-get update
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_OPTIONS} --prefer-source

script:
  - phpunit
